title: Synesthesia
#baseURL:

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-reveal
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-seo
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-bootstrap/v5


############################
## ADVANCED
############################

copyright: '&copy; Julian Elve 2001 - {year}'
disqusShortname: synesthesia-1
enableGitInfo: true
paginate: 10
enableEmoji: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$

permalinks:
  post: '/:year/:month/:day/:slug/'
  note: '/note/:year/:month/:day/:slug/'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
  stream: '/stream/:slug/'

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - headers
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest

imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
timeout: 600000

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    codeFences: true
    noHl: false
    lineNumbersInTable: false
    noClasses: false
    guessSyntax: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
minify:
  tdewolff:
    html:
      keepComments: true


blackfriday:
  hrefTargetBlank: true
  angledQuotes: false
  latexDashes: true
  extensions:
    - backslashLineBreak

enableGitInfo: true

frontmatter:
  date:
  - date
  - lastmod
  - publishDate
  expiryDate:
  - expiryDate
  lastmod:
  - lastmod
  - :git
  - date
  - publishDate
  publishDate:
  - publishDate
  - date
  - :git
  - :filename

cascade:
  commentable: true
  show_related: true
  pager: true

security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
    - ^HUGO_
    - ^WC_
    - ^NOTE_REF_
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*
services:
  RSS:
    Limit: -1

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

