copyright_license:
  enable: true
  allow_derivatives: true
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: M

#theme: minimal
#day_night: true
#font: ''
#font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''

  analytics:
    google_analytics: 'UA-417495-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

features:
  repository:
    url: 'https://github.com/synesthesia/site2019'
    content_dir: content
    branch: master
  privacy_pack_enable: false
  math:
    enable: false
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  avatar:
    gravatar: false
    shape: circle
  comments:
    provider: utterances
    commentable:
      page: true
      reply: true
      post: true
      docs: true
      project: true
      publication: true
      talk: true
      note: true
      stream: true
    disqus:
      shortname: synesthesia-1
      show_count: true
      commento:
      url: ''


# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true


#site_type: Person
#local_business_type: ''
#org_name: ''
#description: ''
#logo: ''
#highlight: true
#math: false
#diagram: false
#privacy_pack: false


sharing_image: ''
#twitter: synesthesia
date_format: 'Jan 2, 2006'
time_format: '15:04'
address_format: en-gb
avatar:
  gravatar: false
  shape: circle
  main_menu:
    enable: true
    align: l
    show_logo: true
    highlight_active_link: true
    show_language: false
    show_day_night: true
    show_search: true
  reading_time: true
  comment_count: true
  section_pager: true
  docs_section_pager: true
  sharing: true
  link_authors: true
  plugins_js: []
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: 3
  commentable:
    page: true
    reply: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
    note: true
    stream: true
  disqus:
    shortname: synesthesia-1
    show_count: true
  commento:
    url: ''

map:
  provider: 0
  api_key: ''
  zoom: 15
marketing:
  google_analytics: UA-417495-1
  google_tag_manager: ''
indieweb:
  github: 'https://github.com/synesthesia'
  linkedin: 'https://www.linkedin.com/in/julianelve/'
  gitlab: 'https://gitlab.com/synesthesia1'
  webmentionio: 'https://webmention.io/www.synesthesia.co.uk'
  fediverse: 'https://social.synesthesia.co.uk/@julian'

# Webmention configuration
webmention:
  enabled: true
  receiver: "https://webmention.io/www.synesthesia.co.uk/webmention"


feed:
  mainSections:
    - post
    - note
    - project
    - event
  streamSections:
    - stream
  stream_sub_types:
    - note
    - bookmark
    - reply
  limit:
    summary: 100



cms:
  netlify_cms: true
  branch: master
#icon:
#  pack:
#    ai: true

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true


security:
  csp:
    policy: >-
      default-src 'self'; frame-src *.synesthesia.co.uk  utteranc.es *.youtube.com *.hypothes.is hypothes.is www.gstatic.com www.gstatic.com/:0;
      connect-src 'self' www.google-analytics.com; script-src 'self' 'unsafe-inline'
      'unsafe-eval' cdn.jsdelivr.net utteranc.es *.google-analytics.com www.google.com www.gstatic.com
      cdnjs.cloudflare.com www.googletagmanager.com identity.netlify.com *.hypothes.is hypothes.is;
      style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com cdn.jsdelivr.net
      fonts.googleapis.com cdn.hypothes.is; img-src *; object-src 'self' data:; media-src *;
      font-src *; base-uri 'self';
    report_only: false
  permissions:
    policy: >-
      accelerometer=(), camera=(), geolocation=(), gyroscope=(),
      magnetometer=(), microphone=(), payment=(), usb=()
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
