branches:
  only:
    - master

image:
  - Visual Studio 2022

cache:
  - node_modules

environment:
  GIT_TOKEN:
    secure: L7sB0mhk4yVtAASxtqQHK6PJwIjjylMgsv7fM5lv6FnBUW083AjOU+LYi/vNnP8z

install:
  - cmd: git submodule update --init --recursive
  - ps: Start-FileDownload 'https://github.com/gohugoio/hugo/releases/download/v0.89.4/hugo_extended_0.89.4_Windows-64bit.zip'
  - ps: mkdir hugo
  - ps: 7z x hugo_extended_0.89.4_Windows-64bit.zip -y
  - cmd: npm i -D postcss-cli

before_build:
  # Output useful info for debugging.
  - hugo version
  - git clone https://github.com/synesthesia/synesthesia.github.io.old.git public

build_script:
  - hugo --gc --minify -b https://synesthesia.github.io -t academic

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:GIT_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email "Julian.Elve@gmail.com"
  - git config --global user.name "Julian Elve"
  - cd public
  - git add .
  - git commit -m "Rebuild"
  - git push origin master
  - cd ..
