[build]
  #command = "hugo --gc --minify -b $URL"
  #command = "npx do-build"
  command = "make build-content"
  publish = "public"
  functions = "functions"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_ENABLEGITINFO = "true"

[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

	[plugins.inputs]
	# If it should show more verbose logs (optional, default = true)
	debug = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"


[context.production.environment]
  HUGO_ENV = "production"

[[context.production.plugins]]
  package = "/plugins/dispatch-webmentions"


[context.staging]
  #command = "netlify-lambda build src/functions && hugo --gc --minify --buildFuture --buildDrafts -b $URL"
  command = "make build-staging"

  [context.staging.environment]
    HUGO_ENV = "staging"



[context.deploy-preview]
  command = "make build-preview-content"

[context.branch-deploy]
  #command = "netlify-lambda build src/functions && hugo --gc --minify -b $URL"
  command = "make build-preview-content"

[[redirects]]
from   = "https://elve.london/*"
to     = "https://www.synesthesia.co.uk/:splat"
status = 301

[[redirects]]
from   = "https://www.elve.london/*"
to     = "https://www.synesthesia.co.uk/:splat"
status = 301

[[redirects]]
from   = "https://elve.co.uk/*"
to     = "https://www.synesthesia.co.uk/:splat"
status = 301

[[redirects]]
from   = "https://www.elve.co.uk/*"
to     = "https://www.synesthesia.co.uk/:splat"
status = 301

[[redirects]]
from   = "https://elve.org.uk/*"
to     = "https://www.synesthesia.co.uk/:splat"
status = 301

[[redirects]]
from   = "https://www.elve.org.uk/*"
to     = "https://www.synesthesia.co.uk/:splat"
status = 301

