[build]
  #command = "hugo --gc --minify -b $URL"
  #command = "yarn do-build"
  command = "make build"
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.91.2"
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

	[plugins.inputs]
	# If it should show more verbose logs (optional, default = true)
	debug = true

[context.production.environment]
  HUGO_ENV = "production"

[[context.production.plugins]]
  package = "/plugins/dispatch-webmentions"


[context.staging]
  #command = "netlify-lambda build src/functions && hugo --gc --minify --buildFuture --buildDrafts -b $URL"
  command = "make build-staging"

  [context.staging.environment]
    HUGO_ENV = "staging"

  

[context.deploy-preview]
  command = "make build-preview"

[context.branch-deploy]
  #command = "netlify-lambda build src/functions && hugo --gc --minify -b $URL"
  command = "make build-preview"
