[build]
  #command = "hugo --gc --minify -b $URL"
  #command = "yarn do-build"
  command = "make build-content"
  publish = "public"
  functions = "functions"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  HUGO_VERSION = "0.91.2"
  HUGO_ENABLEGITINFO = "true"

[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

	[plugins.inputs]
	# If it should show more verbose logs (optional, default = true)
	debug = true

[context.production.environment]
  HUGO_ENV = "production"

[[context.production.plugins]]
  package = "/plugins/dispatch-webmentions"


[context.staging]
  #command = "netlify-lambda build src/functions && hugo --gc --minify --buildFuture --buildDrafts -b $URL"
  command = "make build-staging"

  [context.staging.environment]
    HUGO_ENV = "staging"



[context.deploy-preview]
  command = "make build-preview-content"

[context.branch-deploy]
  #command = "netlify-lambda build src/functions && hugo --gc --minify -b $URL"
  command = "make build-preview-content"

[[redirects]]
https://elve.london/* https://www.synesthesia.co.uk/:splat 200
https://www.elve.london/* https://www.synesthesia.co.uk/:splat 200
https://elve.co.uk/* https://www.synesthesia.co.uk/:splat 200
https://www.elve.co.uk/* https://www.synesthesia.co.uk/:splat 200
https://elve.org.uk/* https://www.synesthesia.co.uk/:splat 200
https://www.elve.org.uk/* https://www.synesthesia.co.uk/:splat 200
