[build]
  #command = "hugo --gc --minify -b $URL"
  command = "yarn prod"
  publish = "do-build"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.58.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $URL"
