[build]
  #command = "hugo --gc --minify -b $URL"
  command = "yarn do-build"
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.63.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.staging.environment]
  HUGO_ENV = "staging"

[context.staging]
  command = "netlify-lambda build src/functions && hugo --gc --minify --buildFuture --buildDrafts -b $URL"

[context.deploy-preview]
  command = "netlify-lambda build src/functions && hugo --gc --minify --buildFuture -b $URL"

[context.branch-deploy]
  command = "netlify-lambda build src/functions && hugo --gc --minify -b $URL"
